name: Frends.Excel.Parse Main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.Excel.Parse/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.Excel.Parse
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      